//! Host-side WIT bindings for the frozen `mailwoman:plugin` world (plan §2.1).
//!
//! Generated by wasmtime's component `bindgen!` from [`wit/plugin.wit`](../wit).
//! `async: true` ⇒ host imports + guest export calls are `async` (so the epoch
//! deadline can preempt a runaway guest); `trappable_imports: true` ⇒ a host
//! import may return either a WIT `plugin-error` (the guest sees it) or a host
//! trap (kills the call). The security core lives in [`crate::host_state`].

wasmtime::component::bindgen!({
    world: "plugin",
    path: "wit",
    // Host imports are `async` (so a runaway guest can be epoch-preempted) and
    // `trappable` (a host import may return either the WIT `plugin-error` the guest
    // sees, or a hard host trap). Guest export calls are `async` for the same reason.
    imports: { default: async | trappable },
    exports: { default: async },
});
