/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const zaDeriveKek: (a: any) => [number, number, number];
export const zaDeriveRootKey: (a: any) => [number, number, number];
export const zaDeriveSubkey: (a: any) => [number, number, number];
export const zaGenerateDataKey: () => [number, number, number];
export const zaLock: (a: any) => [number, number, number];
export const zaLockAll: () => [number, number, number];
export const zaOpenRow: (a: any) => [number, number, number];
export const zaPairComplete: (a: any) => [number, number, number];
export const zaPairGenerate: () => [number, number, number];
export const zaPairSeal: (a: any) => [number, number, number];
export const zaRecoveryPhrase: (a: any) => [number, number, number];
export const zaRestoreFromPhrase: (a: any) => [number, number, number];
export const zaSealRow: (a: any) => [number, number, number];
export const zaUnwrapKey: (a: any) => [number, number, number];
export const zaWrapKey: (a: any) => [number, number, number];
export const __init: () => void;
export const decrypt: (a: any) => [number, number, number];
export const encrypt: (a: any) => [number, number, number];
export const exportBackup: (a: any) => [number, number, number];
export const exportPublic: (a: any) => [number, number, number];
export const generateKey: (a: any) => [number, number, number];
export const importArmored: (a: any) => [number, number, number];
export const importPkcs12: (a: any) => [number, number, number];
export const lockKey: (a: any) => [number, number, number];
export const sign: (a: any) => [number, number, number];
export const unlockKey: (a: any) => [number, number, number];
export const verify: (a: any) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
