/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __init: () => void;
export const decrypt: (a: number, b: number) => void;
export const encrypt: (a: number, b: number) => void;
export const exportBackup: (a: number, b: number) => void;
export const exportPublic: (a: number, b: number) => void;
export const generateKey: (a: number, b: number) => void;
export const importArmored: (a: number, b: number) => void;
export const importPkcs12: (a: number, b: number) => void;
export const lockKey: (a: number, b: number) => void;
export const sign: (a: number, b: number) => void;
export const unlockKey: (a: number, b: number) => void;
export const verify: (a: number, b: number) => void;
export const zaDeriveKek: (a: number, b: number) => void;
export const zaDeriveRootKey: (a: number, b: number) => void;
export const zaDeriveSubkey: (a: number, b: number) => void;
export const zaGenerateDataKey: (a: number) => void;
export const zaLock: (a: number, b: number) => void;
export const zaLockAll: (a: number) => void;
export const zaOpenRow: (a: number, b: number) => void;
export const zaPairComplete: (a: number, b: number) => void;
export const zaPairGenerate: (a: number) => void;
export const zaPairSeal: (a: number, b: number) => void;
export const zaRecoveryPhrase: (a: number, b: number) => void;
export const zaRestoreFromPhrase: (a: number, b: number) => void;
export const zaSealRow: (a: number, b: number) => void;
export const zaUnwrapKey: (a: number, b: number) => void;
export const zaWrapKey: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
