#!/usr/bin/env sh
# First-party plugin-component digest generator (t9-e5-size / plan §7.2, D5).
#
# The server no longer bundles the `.wasm` bridge/plugin components inside its
# binary; it loads them from an external plugins dir at boot and VERIFIES each one
# against a compiled-in SHA-256 digest before it enters the wasmtime jail
# (`crates/mw-server/src/v7_mount.rs` → `FIRST_PARTY_DIGESTS` +
# `resolve_component`). This is the deny-by-default integrity pin: a tampered or
# swapped component fails closed (logged, never silently loaded).
#
# This script recomputes those digests from the canonical shipped layout
# (`plugins/dist/<id>.wasm`) and prints the exact Rust `FIRST_PARTY_DIGESTS`
# table to stdout. It does NOT edit source — paste its output over the table in
# `v7_mount.rs`, then run fmt/clippy/tests.
#
# ── WORKFLOW: "rebuild a component ⇒ regenerate the digest" ───────────────────
#   1. Rebuild the component:  plugins/<name>/build.sh   (emits its .wasm)
#   2. Refresh the shipped copy: cp the rebuilt .wasm to plugins/dist/<id>.wasm
#      (the packaging + resolver reference plugins/dist/ as the canonical layout;
#       plugins/<name>/**/fixtures/*.wasm stay as the crates' own TEST fixtures).
#   3. Run this script and paste the printed table into v7_mount.rs.
#   4. cargo test -p mw-server  (the digest-pin verify must stay green).
# A component whose bytes changed but whose digest was NOT regenerated fails
# closed at boot (integrity, by design).
#
# Usage: plugins/gen-digests.sh
set -eu

cd "$(dirname "$0")/.."
DIST="plugins/dist"

# The stable component ids (0008 plugins.id) → the shipped file <id>.wasm.
IDS="bridge-graph bridge-ews bridge-gmail languagetool nextcloud spam-rspamd spam-spamassassin"

sha256_hex() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

# Emit a hex digest as a Rust `[0xNN, ...; 32]` byte-array literal.
hex_to_rust_array() {
  echo "$1" | sed -E 's/(..)/0x\1, /g' | sed -E 's/, $//'
}

echo "// GENERATED by plugins/gen-digests.sh — do not hand-edit."
echo "// Regenerate whenever a plugins/dist/<id>.wasm is rebuilt (see the script header)."
echo "const FIRST_PARTY_DIGESTS: &[(&str, [u8; 32])] = &["
for id in $IDS; do
  f="$DIST/$id.wasm"
  if [ ! -f "$f" ]; then
    echo "// MISSING: $f" >&2
    exit 1
  fi
  h="$(sha256_hex "$f")"
  echo "    ("
  echo "        \"$id\","
  echo "        [$(hex_to_rust_array "$h")],"
  echo "    ),"
done
echo "];"
