// `deny` (not `forbid`) at the crate root: the pure protocol core is unsafe-free,
// but the `wasm32` component glue generated by `wit-bindgen` in `src/guest.rs` needs
// `unsafe` for the WASI-p2 ABI lift/lower, so that module re-enables it locally
// (`#![allow(unsafe_code)]`). The host trust boundary is `mw-plugin` (which IS
// `#![forbid(unsafe_code)]`); a guest component's ABI shim is not that boundary.
#![deny(unsafe_code)]
//! `bridge-ews` — on-prem Microsoft Exchange (EWS) account-backend bridge
//! (plan §3 e11, SPEC §6.5). **CUT-PROOF.**
//!
//! A first-party **`wasm32-wasip2` engine plugin**: it implements the frozen
//! `mailwoman:plugin` `account-backend` (+ `addrbook-source`) WIT exports over an
//! **EWS SOAP subset** (`quick-xml`), so once loaded through `mw-plugin` the engine
//! cannot tell it from `mw-imap`. The guest never opens a socket — every request
//! goes through the host `http-fetch` import under the manifest `net_allowlist`.
//!
//! Coverage: mail sync (`SyncFolderHierarchy`/`SyncFolderItems`), MIME fetch
//! (`GetItem`), send (`CreateItem`/`SendAndSaveCopy`), read-flag/move, GAL
//! (`ResolveNames`), calendar create/list, free/busy (`GetUserAvailability`), room
//! lists/rooms, Out-of-Office (`GetUserOofSettings`), the honest message-recall
//! path, and Outlook voting buttons.
//!
//! ## Auth (plan §3 e11, R2)
//! **Basic + pure-Rust NTLMv2** ([`ntlm`], over the hand-rolled [`md`] primitives —
//! zero new dependencies, no GSSAPI/C). **Kerberos is a DOCUMENTED GAP:** pure-Rust
//! Kerberos/GSSAPI is not viable within the permissive license floor, so
//! Kerberos-SSO is a **BYO-reverse-proxy-auth** deployment path, tracked as a
//! post-1.0 native item — the bridge never pretends to do Kerberos.
//!
//! ## Crate shape
//! The pure protocol core ([`md`]/[`ntlm`]/[`soap`]/[`ews`]/[`pim`]/[`wire`])
//! compiles on every target and is unit-tested on the host against the
//! recorded fixtures under `fixtures/`. The WIT component glue + host-mediated
//! transport ([`guest`]) is `wasm32`-only, so `cargo build --workspace` stays green
//! on the host while `cargo build --target wasm32-wasip2` produces the component.

pub mod ews;
pub mod md;
pub mod ntlm;
pub mod pim;
pub mod soap;
pub mod wire;

#[cfg(target_arch = "wasm32")]
mod guest;

/// The manifest plugin id (matches `plugin.toml`).
pub const PLUGIN_ID: &str = "bridge-ews";

/// The EWS endpoint host the bridge talks to. In production the concrete endpoint +
/// credentials are bound per-account by the mount layer (e14) via the scoped host
/// KV / sealed-credential seam; the fixtures use this placeholder host, which the
/// plugin manifest lists in its `net_allowlist` (so the host `http-fetch` gate
/// admits it and nothing else).
pub const ENDPOINT_HOST: &str = "ews.example.com";

/// The full EWS SOAP endpoint URL derived from [`ENDPOINT_HOST`].
pub const ENDPOINT_URL: &str = "https://ews.example.com/EWS/Exchange.asmx";

#[must_use]
pub fn plugin_id() -> &'static str {
    PLUGIN_ID
}
